// Copyright 2021 Michael Treanor. All rights reserved.
// Use of this source code is governed the MIT License
// that can be found in the LICENSE file.

// Package gogen implements automation for Go code generation
// using go generate and templates.
//
// usage example:
//
// $ gogen maketests.go
//
// $ go run maketests.go -output benchmarks.go
//
package gogen

import (
	"fmt"
	"log"
	"strings"
	"time"
)

var defaultUserConfig = &UserConfig{
	Name:                 "Michael Treanor",
	Email:                "skeptycal@gmail.com",
	Username:             "skeptycal",
	DefaultLicense:       "MIT",
	DefaultCopyrightYear: fmt.Sprintf("%d", time.Now().Year()),
}

const (
	fmtCopyrightHeader = `// Copyright (c) %s %s. All rights reserved.
// Use of this source code is governed the %s License
// that can be found in the LICENSE file.

`
	fmtCodeGenNotice = "// Code generated by go run %s -output %s; DO NOT EDIT.\n\n"

	fmtPackage       = "package %s"
	fmtMemo          = "// %s"
	fmtSectionCloser = "}\n\n"
	fmtFuncHeader    = "//%s is an automatically generated function.\nfunc %s (%s) %s {\n"
	fmtStructHeader  = "//%s is an automatically generated struct.\ntype %s struct {\n"
	fmtTableHeader   = "//%s is an automatically generated table.\nvar %s %s = %s{\n"
)

type UserConfig struct {
	Name                 string `default:"defaultUserConfig.Name"`
	Email                string `default:"defaultUserConfig.Email"`
	Username             string `default:"defaultUserConfig.Username"`
	DefaultLicense       string `default:"defaultUserConfig.DefaultLicense"`
	DefaultCopyrightYear string `default:"defaultUserConfig.DefaultCopyrightYear"`
}

func (c *UserConfig) String() string {
	sb := strings.Builder{}
	defer sb.Reset()
	sb.WriteString("User Config:\n")
	sb.WriteString("Name: " + c.Name + "\n")
	sb.WriteString("Email: " + c.Email + "\n")
	sb.WriteString("Username: " + c.Username + "\n")
	sb.WriteString("DefaultLicense: " + c.DefaultLicense + "\n")
	sb.WriteString("DefaultCopyrightYear: " + c.DefaultCopyrightYear + "\n")
	return sb.String()
}

type RepoConfig struct {
	User        *UserConfig
	name        string
	license     string `default:""`
	year        string `default:""`
	url         string `default:""`
	downloadURL string `default:""`
	docURL      string `default:""`
}

func NewUserConfig(name, email, username, defaultLicense, defaultCopyrightYear string) *UserConfig {

	// if name == "" {
	//     name = defaultUserConfig.Name
	// }
	// if email == "" {
	//     email = defaultUserConfig.Email
	// }
	// if username == "" {
	//     username = defaultUserConfig.Username
	// }
	// if defaultLicense == "" {
	//     defaultLicense = defaultUserConfig.DefaultLicense
	// }
	// if defaultCopyrightYear == "" {
	//     defaultCopyrightYear = defaultUserConfig.DefaultCopyrightYear
	// }

	return &UserConfig{
		Name:                 name,
		Email:                email,
		Username:             username,
		DefaultLicense:       defaultLicense,
		DefaultCopyrightYear: defaultCopyrightYear,
	}
}

func NewRepoConfig(reponame string, user *UserConfig) (rc *RepoConfig) {
	if user == nil {
		user = defaultUserConfig
	}
	if reponame == "" {
		log.Fatal("a repo name is required")
	}

	rc = &RepoConfig{
		User: user,
		name: reponame,
	}

	return
}

func (r *RepoConfig) DownloadURL() string {
	if r.name == "" {
		log.Fatalf("a valid repo name is required")
	}
	return fmt.Sprintf("https://github.com/%s/%s", r.User.Username, r.name)
}

func (r *RepoConfig) DocURL() string {
	if r.name == "" {
		log.Fatalf("a valid repo name is required")
	}
	if r.docURL == "" {
		r.docURL = fmt.Sprintf("https://github.com/%s/%s/docs", r.User.Username, r.name)
	}
	return r.docURL
}

func (r *RepoConfig) URL() string {
	if r.name == "" {
		log.Fatalf("a valid repo name is required")
	}
	if r.url == "" {
		r.url = fmt.Sprintf("https://%s.github.io/%s", r.User.Name, r.name)
	}
	return r.url
}

func (r *RepoConfig) genPageTemplate() string {
	sb := strings.Builder{}
	defer sb.Reset()

	sb.WriteString(r.genCopyrightHeader())
	// todo -
	return sb.String()
}

func (r *RepoConfig) genCopyrightHeader() string {
	return fmt.Sprintf(fmtCopyrightHeader, r.year, r.User.Name, r.license)
}

func (r *RepoConfig) genPackage() string {
	return fmt.Sprintf(fmtPackage, r.name)
}

func (r *RepoConfig) genMemo(memo string) string {
	return fmt.Sprintf(fmtMemo, memo)
}

func genClose() string { return fmtSectionCloser }

func (r *RepoConfig) genFuncHeader(name, args, retvals string) string {
	return fmt.Sprintf(fmtFuncHeader, name, name, args, retvals)
}

func (r *RepoConfig) genStructHeader(name string) string {
	return fmt.Sprintf(fmtStructHeader, name, name)
}

func (r *RepoConfig) genTableHeader(name, vartype, value string) string {
	return fmt.Sprintf(fmtTableHeader, name, name, vartype, value)
}
